export const DB_NAME = "classsync";
export const GENERIC_TEACHER_SCHEDULE = {
    mon: {
        "08-09": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "09-10": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "10-11": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "11-12": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "12-01": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "01-02": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "02-03": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "03-04": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "04-05": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "05-06": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
    },
    tue: {
        "08-09": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "09-10": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "10-11": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "11-12": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "12-01": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "01-02": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "02-03": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "03-04": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "04-05": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "05-06": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
    },
    wed: {
        "08-09": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "09-10": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "10-11": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "11-12": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "12-01": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "01-02": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "02-03": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "03-04": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "04-05": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "05-06": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
    },
    thu: {
        "08-09": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "09-10": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "10-11": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "11-12": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "12-01": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "01-02": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "02-03": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "03-04": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "04-05": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "05-06": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
    },
    fri: {
        "08-09": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "09-10": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "10-11": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "11-12": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "12-01": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "01-02": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "02-03": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "03-04": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "04-05": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "05-06": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
    },
    sat: {
        "08-09": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "09-10": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "10-11": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "11-12": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "12-01": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "01-02": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "02-03": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "03-04": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "04-05": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "05-06": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
    },
    sun: {
        "08-09": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "09-10": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "10-11": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "11-12": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "12-01": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "01-02": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "02-03": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "03-04": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "04-05": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
        "05-06": {
            course: "",
            semester: "",
            section: [],
            roomid: [],
            subjectcode: "",
        },
    },
};
