import type { Config } from "tailwindcss";

const config: Config = {
    content: ["./src/**/*.{js,ts,jsx,tsx}"], // Adjust this path based on your project
    theme: {
        extend: {
            colors: {
                "brand": {
                    "red": "#dc3545",
                    "cyan": "#016a89d3",
                },
                "bg-primary": "#007bff",
                "bg-secondary": "#6c757d",
                "bg-success": "#28a745",
                "bg-danger": "#dc3545",
                "bg-warning": "#ffc107",
                "bg-info": "#17a2b8",
                "bg-light": "#f8f9fa",
                "bg-dark": "#343a40",
                "bg-black": "#000000",
                "bg-white": "#ffffff",
                "bg-background": "#f8f9fa",
                "bg-red": "#fb4934",
                "bg-green": "#b8bb26",
                "bg-yellow": "#fabd2f",
                "bg-blue": "#83a598",
                "bg-purple": "#d3869b",
                "bg-aqua": "#8ec07c",
                "bg-orange": "#fe8019",
                "bg-gray": "#918273",

                "dim-red": "#cc2412",
                "dim-green": "#98971a",
                "dim-yellow": "#d79921",
                "dim-blue": "#458588",
                "bright-blue": "#1b8085",
                "dim-purple": "#b16286",
                "dim-aqua": "#699d6a",
                "dim-orange": "#d65d0e",
                "dim-gray": "#a89984",
                "hard-background": "#1d2021",
                "medium-background": "#282828",
                "soft-background": "#323027",
                "background-1": "#3c3836",
                "background-2": "#504945",
                "background-3": "#665c54",
                "background-4": "#7c6764",
                "foreground": "#fbf1c7",
                "foreground-1": "#ebdbb2",
                "foreground-2": "#d5c4a1",
                "foreground-3": "#bdae93",
                "foreground-4": "#a89984",
                vim: {
                    "dark0": "#0d0e0f",
                    "dark": "#202020",
                    "background-dark": "#242424",
                    "background": "#282828",
                    "background-light": "#32302f",
                    "foreground": "#ebdbb2",
                    "gray": "#dedede",
                    "medium-gray": "#504945",
                    "comment": "#665c54",
                    "milk": "#e7d7ad",
                    "error-red": "#cc241d",
                    "red": "#fb4934",
                    "orange": "#d65d0e",
                    "bright-yellow": "#fabd2f",
                    "soft-yellow": "#eebd35",
                    "pink": "#d4879c",
                    "magenta": "#b16286",
                    "soft-green": "#98971a",
                    "forest-green": "#689d6a",
                    "clean-green": "#8ec07c",
                    "blue-gray": "#458588",
                    "dark-gray": "#83a598",
                    "light-blue": "#7fa2ac",
                },
            },
        },
    },
    plugins: [],
};

export default config;
