export const localhost = "https://class-sync-azure.azurewebsites.net";
export const room_type_options = ["class", "hall", "computerlab", "englishlab", "electroniclab", "mechanicallab", "civillab", "drawinglab", "physicslab", "chemistrylab", "ladieswashroom", "gentswashroom", "office", "staffroom", "other"];

// const localhost = "http://localhost:3000";
export const room_default_schedule = {
    "mon": {
        "08-09": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "09-10": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "10-11": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "11-12": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "12-01": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "01-02": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "02-03": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "03-04": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "04-05": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "05-06": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" }
    },
    "tue": {
        "08-09": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "09-10": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "10-11": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "11-12": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "12-01": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "01-02": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "02-03": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "03-04": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "04-05": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "05-06": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" }
    },
    "wed": {
        "08-09": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "09-10": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "10-11": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "11-12": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "12-01": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "01-02": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "02-03": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "03-04": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "04-05": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "05-06": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" }
    },
    "thu": {
        "08-09": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "09-10": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "10-11": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "11-12": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "12-01": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "01-02": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "02-03": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "03-04": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "04-05": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "05-06": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" }
    },
    "fri": {
        "08-09": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "09-10": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "10-11": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "11-12": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "12-01": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "01-02": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "02-03": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "03-04": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "04-05": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "05-06": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" }
    },
    "sat": {
        "08-09": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "09-10": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "10-11": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "11-12": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "12-01": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "01-02": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "02-03": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "03-04": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "04-05": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "05-06": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" }
    },
    "sun": {
        "08-09": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "09-10": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "10-11": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "11-12": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "12-01": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "01-02": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "02-03": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "03-04": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "04-05": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" },
        "05-06": { "course": "", "semester": "", "section": [], "teacherid": "", "subjectcode": "" }
    }
}
export const faculty_default_schedule = {
    "mon": {
        "08-09": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "09-10": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "10-11": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "11-12": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "12-01": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "01-02": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "02-03": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "03-04": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "04-05": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "05-06": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
    },
    "tue": {
        "08-09": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "09-10": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "10-11": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "11-12": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "12-01": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "01-02": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "02-03": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "03-04": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "04-05": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "05-06": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
    },
    "wed": {
        "08-09": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "09-10": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "10-11": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "11-12": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "12-01": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "01-02": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "02-03": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "03-04": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "04-05": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "05-06": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
    },
    "thu": {
        "08-09": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "09-10": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "10-11": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "11-12": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "12-01": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "01-02": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "02-03": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "03-04": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "04-05": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "05-06": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
    },
    "fri": {
        "08-09": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "09-10": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "10-11": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "11-12": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "12-01": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "01-02": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "02-03": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "03-04": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "04-05": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "05-06": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
    },
    "sat": {
        "08-09": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "09-10": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "10-11": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "11-12": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "12-01": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "01-02": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "02-03": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "03-04": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "04-05": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "05-06": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
    },
    "sun": {
        "08-09": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "09-10": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "10-11": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "11-12": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "12-01": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "01-02": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "02-03": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "03-04": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "04-05": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
        "05-06": { course: "", semester: "", section: [], roomid: [], subjectcode: "" },
    },
}